### ISSUE TITLE
Scriptable ship controls

### ISSUE THREAD

**Issue by madbence** [madbence/spacegame#135]
- should run on the browser
- it should have access to the low-level game api
  - dispatch actions
  - simulate state

**Comment by Thegaram** [comment]
My idea was to run the control code in a web worker.
1. The user can define custom controls (e.g. keyboard listeners) in the init part. This would default to the current W-A-D-Space controls.
2. The worker periodically receives the game state (in each simulation step?) and it could send actions back, in a loop.

This way the user would have the choice to refine controls, or even code a proper AI (and maybe even change it during the game). The rendering logic would be separated (allowing users to be just spectators) and there could be a central unit coordinating rendering, simulation, and communication with the worker. I will investigate this approach.

**Comment by Thegaram** [comment]
I've been experimenting with this. There's an example solution (for a counter) here:
https://github.com/Thegaram/js_sandbox_example

The Sandbox module (running dynamic, user-defined code) works like this:
1. The user's code defines certain methods (init, react, cleanup)
2. The code is surrounded by some additional code for providing some useful functions, hiding globals we don't want it to have access to and managing messages
3. The resulting code is compiled on-the-fly with babel
4. The compiled code is run in a new web worker instance
5. The code can be terminated from outside anytime

The code in the sandbox communicates with the outside world via messages and event handlers.

I'm not sure it's the best way to solve this, but it seems to work. I appreciate any feedback. I will look into integrating this into the game.

**Comment by madbence** [comment]
:+1: great!

babel is great, but it's huge (afaik, but will check), we should not allow the bundle to grow too big, maybe we'll need [`factor-bundle`](https://www.npmjs.com/package/factor-bundle).

i see multiple options for implementations:

### user-provided `init` and `handle`, which is called periodically by the system

``` js
/**
 * simulate :: (State, Action) -> State
 * handle :: State -> ()
 */
function init(actions, simulate) {
  return function handle(state) {
    actions.thrust(thruster, strength); // etc
  }
}
```

### user-provided `init`, and everything is handled by the user

``` js
function init(actions, simulate, getState) {
  setInterval(function () {
    actions.thrust(thruster, strength);
  }, 1234);
}
```

**Comment by Thegaram** [comment]
My idea was that simulation is still handled by us, with the current state sent to the user script on every simulation step (or any other update). This, of course, puts some time constraints on the script. Also, queuing of the updates might be problematic.

**Comment by madbence** [comment]
i mean the user can simulate state too (so the user can observe the effect without actually performing the action), but yeah that's just a convinience feature. the problem right now is that there is no _simulation step_, there is no _tick_ event, everything is computed just before it's needed

**Comment by Thegaram** [comment]
There _is_ some kind of simulation step, right?

``` javascript
simulate(this.cachedState, noop(Date.now() - this.offset));
```

on every rendering. Of course, it could be decoupled from rendering and made more "regular". But now that you explained, I actually like the idea of `simulate` on the user side. I will check your second suggestion, it seems fairly easy to use.

**Comment by madbence** [comment]
yep, that's used for rendering, and it is _optimistic_. the actual game state might be different on the server (network latency), so this state might rolled back to a well-known state (everyone agrees on the timing of user actions, so the last executed action is the "_checkpoint_")

**Comment by Thegaram** [comment]
There's a working prototype of this on the branch `feat/add_code_sandbox`.

The user code is in components/game for now, eventually it would be read from an editor. The interface available to the user consists of `getState`, `actions.accelerate`, `actions.fire` and `helpers.addKeyListener`.

TODO:
- Add `simulate` so that the user can try actions without executing them.
- Implement UI (i.e. editor and a field for error messages)
- Figure out a way to share code between worker code and the rest (e.g. for message types)
- Rethink code structure
- Extend interface with additional actions/helpers

**Comment by madbence** [comment]
:+1: i'll review it on friday :wink:
