### ISSUE TITLE
Code reviews

### ISSUE THREAD

**Issue by madbence** [madbence/spacegame#155]
i think we should implement a simple review process before merging pull requests
### my proposal

for daily work, our team (@purposeindustries) developed a similar, very simple process:
1. work in feature branch
2. push & create pr
3. if you're ready, put a `review-needed` label on it (it should pass travis tests)
4. someone else reviews it, removes `review-needed` label, puts `ready-to-merge` label
5. pr opener rebases the brach onto `master` & fast-forwards `master`

feedback is welcomed :wink: @Thegaram

**Comment by Thegaram** [comment]
I like the idea :)

**Comment by madbence** [comment]
ok then :smile:
