### ISSUE TITLE
Simplify require paths

### ISSUE THREAD

**Issue by madbence** [madbence/spacegame#156]
`../../../foo/bar` is ugly. there are several options to simplify this:
### symlink from node modules

eg `node_modules/server -> src/server`, so everything can be imported like `server/x/y` or `client/x/y` etc. this works on windows too afaik. setup is a bit fragile, since you need a `postinstall` script that links stuff.
### submodules

eg. move `src/server` to `node_modules/server` (and add them to git), etc. makes dep reinstall quite hard, since you usually just do `$ rm -rf node_modules && npm i`.
### `$NODE_PATH`

set `$NODE_PATH` to `src`. this might work on windows too, but i'm not sure that the syntax is supported (eg. `$ NODE_PATH=./src babel-node src/server/app`)
### local modules

modules can be installed from local directories, but then we have to maintain their own `package.json` files, etc.

i have experience with the symlink approach, it definitely works. i have tried also local modules and simple submodules, but they are weird (but they do work). i was not aware about `$NODE_PATH` until a few months, but it looks nice (if it works on windows).

**Comment by Thegaram** [comment]
Another way:
a) https://www.npmjs.com/package/remapify. This is for browserify.
b) https://www.npmjs.com/package/app-module-path. This is for Node.

The combination of these two would probably work. But I'd rather go the `$NODE_PATH` way.
